export const NAVIGATION = [
  {
    name: 'navigation.home',
    link:'/',
  },
  {
    name:'navigation.services',
    link:'/services',
  },
  {
    name:'navigation.project',
    link:'/page-2',
  },
  {
    name:'navigation.product',
    link:'/page-2',
  },
  {
    name:'navigation.careers',
    link:'/page-2',
  },
  {
    name:'navigation.about_us',
    link:'/page-2',
  },
  {
    name:'navigation.contact',
    link:'/page-2',
  }
]
